apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  PORT: $PORT
  apiKey: $apiKey
  authDomain: $authDomain
  projectId: $projectId
  storageBucket: $storageBucket
  messagingSenderId: $messagingSenderId
  appId: $appId
  measurementId: $measurementId
  foldername: $foldername

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: bytecode-executor-ms
spec:
  replicas: 4
  selector:
    matchLabels:
      app: bytecode-executor-ms
  template:
    metadata:
      labels:
        app: bytecode-executor-ms
    spec:
      containers:
      - name: bytecode-executor-ms
        image: kunalsahay/bytecode-executor
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
          - configMapRef:
              name: my-config

---

apiVersion: v1
kind: Service
metadata:
  name: bytecode-executor-service
spec:
  type: LoadBalancer
  selector:
    app: bytecode-executor-ms
  ports:
    - port: 80
      targetPort: 8000
